services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: adodas
      MYSQL_DATABASE: adodas
    ports:
      - "3306:3306"
    restart: unless-stopped

  api:
    build: .
    container_name: adodas-api
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    restart: unless-stopped
