# Base de datos PROD (AWS o remoto)
spring.datasource.url=jdbc:mariadb://TU_HOST_PROD:3306/adodas
spring.datasource.username=admin
spring.datasource.password=password_seguro
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
logging.level.org.springframework=ERROR